# Generated by Django 3.2.4 on 2023-09-20 17:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0009_myorder'),
    ]

    operations = [
        migrations.RenameField(
            model_name='register',
            old_name='Address',
            new_name='address',
        ),
    ]
