# Generated by Django 3.2.4 on 2023-09-13 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_products'),
    ]

    operations = [
        migrations.CreateModel(
            name='register',
            fields=[
                ('name', models.CharField(max_length=150, null=True)),
                ('email', models.CharField(max_length=100, primary_key=True, serialize=False)),
            ],
        ),
        migrations.AlterField(
            model_name='products',
            name='product_pic',
            field=models.ImageField(null=True, upload_to='static/product/'),
        ),
        migrations.AlterField(
            model_name='products',
            name='product_quantity',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
