# Generated by Django 3.2.4 on 2023-09-13 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_auto_20230913_0904'),
    ]

    operations = [
        migrations.AddField(
            model_name='register',
            name='Address',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='register',
            name='mobile',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='register',
            name='passwd',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='register',
            name='profile',
            field=models.ImageField(null=True, upload_to='static/userpic/'),
        ),
    ]
